### ISSUE TITLE
Rename `AmazonS3FileSystem` to `S3FileSystem`

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-objectstore-s3#35]
I was looking at the C++/Python Apache Arrow docs and saw they use the name `S3FileSystem` (https://arrow.apache.org/docs/search.html?q=s3).  While we of course dont need to follow their lead I do think that using that naming makes more sense given that this doesnt need to connect to Amazon S3 (while they are the standard bearer).  

we of course are using the official amazon library to connect(im not sure if the C++/Python implementation is), and im not sure if that was taken into account when naming.

one more example is pythons `s3fs` which is built on top of `botocore` another aws library. 

@seddonm1 what do you think? if ok with you i will make the update.

**Comment by seddonm1** [comment]
I think that technically it is the Amazon S3 API that has been implemented by Amazon and the other players so the current naming is probably correct: https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html

Either way, I'm not sure many users will ever even see this layer?

**Comment by matthewmturner** [comment]
I guess my point was more even in cases when an official Amazon library is used under the hood (i.e. `s3fs` using `botocore`) the name 'Amazon' still was not included in the primary file system object (they use `S3FileSysem` (https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem).  And then there is the Arrow C++/Python implementation which also uses `S3FileSystem`.

I know its not a big deal, but it seems `S3FileSystem` is the norm and it would be nice to have a shorter name :)

**Comment by seddonm1** [comment]
Go for it if you want 👍
