### ISSUE TITLE
Doc-test for `register_object_store` not working 

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-objectstore-s3#39]
I cant get doc tests to pass using the `object_store` returned from `ctx.object_store` method (i get file not found error).  Does anything seem off to you @seddonm1?

_Originally posted by @matthewmturner in https://github.com/datafusion-contrib/datafusion-objectstore-s3/pull/38#discussion_r800304204_

**Comment by seddonm1** [comment]
it's not particularly beautiful but it does demonstrate how it works

**Comment by seddonm1** [comment]
alternatively we move this logic in to the actual `S3FileSystem` and make sure all input URIs are `s3:://` prefixed

**Comment by matthewmturner** [comment]
> alternatively we move this logic in to the actual `S3FileSystem` and make sure all input URIs are `s3:://` prefixed

That sounds reasonable.  Just one question.

Does that mean users would need to input file paths with a full "s3://" + "BUCKET" prefix before the actual table path?

**Comment by seddonm1** [comment]
yes so `s3://data/alltypes_plain.snappy.parquet` indicates scheme `s3://`, bucket `data` and file `alltypes_plain.snappy.parquet`. The reason your previous code was failing as `ctx.object_store(uri)?` matches on the scheme `s3://` (including `://`).

**Comment by matthewmturner** [comment]
Noted - thank you for explanation.

**Comment by matthewmturner** [comment]
@seddonm1 actually since only the `ObjectStoreRegistry` is using the uri - do we need to add anything in `S3FileSystem`?  For example, we dont currently have "s3://" in any paths that we use for tests and have no issues.  I think I just misunderstood how to use the `ctx.object_store` API.
