### ISSUE TITLE
Support aws_config::load_from_env()

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-objectstore-s3#5]
As @seddonm1 notes, `aws_config::load_from_env()` doesnt allow specifying endpoint which is required for integration testing.

that being said, it would still be nice to support this feature.  

Maybe we could add a boolean argument to `AmazonS3FileSystem::new` like `load_from_env` and dispatch accordingly.

**Comment by seddonm1** [comment]
Im not 100% sure but i think if you pass all `None` values to the default credentials provider will do the env vars. I don't have an S3 bucket to test with though.

**Comment by matthewmturner** [comment]
I believe i tested that before and had same issue, but i will give it a try again.

**Comment by matthewmturner** [comment]
Yeah i get `Error: Internal("ConstructionFailure(MissingCredentials)")` when everything is set to None except `bucket` in `AmazonS3FileSystem::new`
